# Generated by Django 2.0.7 on 2019-01-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20190107_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitrequests',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
    ]
